[package]
name = "coderty"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6"
ethers = "2"
dotenv = "0.15.0"
tokio = { version = "1.19", features = ["full"] }
clap = { version = "4.3.21", features = ["derive", "env"] }
