#![allow(clippy::all)]
//! This module contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod address;
pub mod checkpoints;
pub mod context;
pub mod contributions;
pub mod counters;
pub mod double_ended_queue;
pub mod ecdsa;
pub mod eip712;
pub mod erc165;
pub mod erc721;
pub mod erc721_votes;
pub mod governor;
pub mod governor_counting_simple;
pub mod governor_settings;
pub mod governor_votes;
pub mod governor_votes_quorum_fraction;
pub mod i_governor;
pub mod i_votes;
pub mod ierc1155_receiver;
pub mod ierc165;
pub mod ierc5267;
pub mod ierc5805;
pub mod ierc6372;
pub mod ierc721;
pub mod ierc721_metadata;
pub mod ierc721_receiver;
pub mod math;
pub mod ownable;
pub mod project;
pub mod safe_cast;
pub mod short_strings;
pub mod signed_math;
pub mod storage_slot;
pub mod strings;
pub mod votes;
